# Generated by Django 4.2.7 on 2023-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sumup_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
