# Generated by Django 5.0 on 2023-12-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_sumup_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
