# Generated by Django 5.0 on 2023-12-29 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_merchant_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('display_resolution', models.CharField(max_length=255)),
                ('android_version', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(max_length=255)),
                ('country_location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_cordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
