# Generated by Django 5.0 on 2024-01-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='amountInPounds',
            new_name='amount_in_pounds',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='merchantCode',
            new_name='merchant_code',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='productInformation',
            new_name='product_information',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='transactionCode',
            new_name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='donor',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
