# Generated by Django 5.0 on 2024-01-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_amountinpounds_donor_amount_in_pounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='amount_in_pounds',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='postcode',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='timestamp',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='transaction_code',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
