# Generated by Django 5.0 on 2024-01-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_donor_address_alter_donor_amount_in_pounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='transaction_code',
            field=models.CharField(max_length=255),
        ),
    ]
