# Generated by Django 5.0 on 2024-01-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_donor_subscribe_alter_donor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount_in_pounds',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
