# Generated by Django 5.0 on 2024-01-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_donor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
